// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;

/**
 * AddressId generated by hbm2java
 */
public class AddressId implements java.io.Serializable {

	private String empId;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String country;
	private byte[] valid;
	private String phone1;
	private String phone2;

	public AddressId() {
	}

	public AddressId(String empId, String address1, String address2,
			String city, String state, String country, byte[] valid,
			String phone1, String phone2) {
		this.empId = empId;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.valid = valid;
		this.phone1 = phone1;
		this.phone2 = phone2;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public byte[] getValid() {
		return this.valid;
	}

	public void setValid(byte[] valid) {
		this.valid = valid;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressId))
			return false;
		AddressId castOther = (AddressId) other;

		return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
				&& castOther.getEmpId() != null && this.getEmpId().equals(
				castOther.getEmpId())))
				&& ((this.getAddress1() == castOther.getAddress1()) || (this
						.getAddress1() != null
						&& castOther.getAddress1() != null && this
						.getAddress1().equals(castOther.getAddress1())))
				&& ((this.getAddress2() == castOther.getAddress2()) || (this
						.getAddress2() != null
						&& castOther.getAddress2() != null && this
						.getAddress2().equals(castOther.getAddress2())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null
						&& castOther.getCity() != null && this.getCity()
						.equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getValid() == castOther.getValid()) || (this
						.getValid() != null && castOther.getValid() != null && Arrays
							.equals(this.getValid(), castOther.getValid())))
				&& ((this.getPhone1() == castOther.getPhone1()) || (this
						.getPhone1() != null && castOther.getPhone1() != null && this
						.getPhone1().equals(castOther.getPhone1())))
				&& ((this.getPhone2() == castOther.getPhone2()) || (this
						.getPhone2() != null && castOther.getPhone2() != null && this
						.getPhone2().equals(castOther.getPhone2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmpId() == null ? 0 : this.getEmpId().hashCode());
		result = 37 * result
				+ (getAddress1() == null ? 0 : this.getAddress1().hashCode());
		result = 37 * result
				+ (getAddress2() == null ? 0 : this.getAddress2().hashCode());
		result = 37 * result
				+ (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		int validHashcode = 0;
		byte[] validProperty = this.getValid();
		if (validProperty != null) {
			validHashcode = 1;
			for (int i = 0; i < validProperty.length; i++) {
				validHashcode = 37 * validHashcode + validProperty[i];
			}
		}

		result = 37 * result + validHashcode;

		result = 37 * result
				+ (getPhone1() == null ? 0 : this.getPhone1().hashCode());
		result = 37 * result
				+ (getPhone2() == null ? 0 : this.getPhone2().hashCode());
		return result;
	}

}
