// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private AddressId id;

	public Address() {
	}

	public Address(AddressId id) {
		this.id = id;
	}

	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

}
