// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private ClientId id;

	public Client() {
	}

	public Client(ClientId id) {
		this.id = id;
	}

	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

}
