// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Education generated by hbm2java
 */
public class Education implements java.io.Serializable {

	private EducationId id;

	public Education() {
	}

	public Education(EducationId id) {
		this.id = id;
	}

	public EducationId getId() {
		return this.id;
	}

	public void setId(EducationId id) {
		this.id = id;
	}

}
