// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * EmployeeId generated by hbm2java
 */
public class EmployeeId implements java.io.Serializable {

	private String empId;
	private String username;
	private String fname;
	private String lname;
	private String dob;
	private String email;
	private String password;

	public EmployeeId() {
	}

	public EmployeeId(String empId, String username, String fname,
			String lname, String dob, String email, String password) {
		this.empId = empId;
		this.username = username;
		this.fname = fname;
		this.lname = lname;
		this.dob = dob;
		this.email = email;
		this.password = password;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeId))
			return false;
		EmployeeId castOther = (EmployeeId) other;

		return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
				&& castOther.getEmpId() != null && this.getEmpId().equals(
				castOther.getEmpId())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getFname() == castOther.getFname()) || (this
						.getFname() != null && castOther.getFname() != null && this
						.getFname().equals(castOther.getFname())))
				&& ((this.getLname() == castOther.getLname()) || (this
						.getLname() != null && castOther.getLname() != null && this
						.getLname().equals(castOther.getLname())))
				&& ((this.getDob() == castOther.getDob()) || (this.getDob() != null
						&& castOther.getDob() != null && this.getDob().equals(
						castOther.getDob())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmpId() == null ? 0 : this.getEmpId().hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getFname() == null ? 0 : this.getFname().hashCode());
		result = 37 * result
				+ (getLname() == null ? 0 : this.getLname().hashCode());
		result = 37 * result
				+ (getDob() == null ? 0 : this.getDob().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		return result;
	}

}
