// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Experience generated by hbm2java
 */
public class Experience implements java.io.Serializable {

	private ExperienceId id;

	public Experience() {
	}

	public Experience(ExperienceId id) {
		this.id = id;
	}

	public ExperienceId getId() {
		return this.id;
	}

	public void setId(ExperienceId id) {
		this.id = id;
	}

}
