// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExperienceId generated by hbm2java
 */
public class ExperienceId implements java.io.Serializable {

	private String empId;
	private String title;
	private String company;
	private String year;
	private Integer order;

	public ExperienceId() {
	}

	public ExperienceId(String empId, String title, String company,
			String year, Integer order) {
		this.empId = empId;
		this.title = title;
		this.company = company;
		this.year = year;
		this.order = order;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExperienceId))
			return false;
		ExperienceId castOther = (ExperienceId) other;

		return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
				&& castOther.getEmpId() != null && this.getEmpId().equals(
				castOther.getEmpId())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getCompany() == castOther.getCompany()) || (this
						.getCompany() != null && castOther.getCompany() != null && this
						.getCompany().equals(castOther.getCompany())))
				&& ((this.getYear() == castOther.getYear()) || (this.getYear() != null
						&& castOther.getYear() != null && this.getYear()
						.equals(castOther.getYear())))
				&& ((this.getOrder() == castOther.getOrder()) || (this
						.getOrder() != null && castOther.getOrder() != null && this
						.getOrder().equals(castOther.getOrder())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmpId() == null ? 0 : this.getEmpId().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37 * result
				+ (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result
				+ (getOrder() == null ? 0 : this.getOrder().hashCode());
		return result;
	}

}
