// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectId generated by hbm2java
 */
public class ProjectId implements java.io.Serializable {

	private String projectId;
	private String projectName;
	private String projectDetails;

	public ProjectId() {
	}

	public ProjectId(String projectId, String projectName, String projectDetails) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectDetails = projectDetails;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(String projectDetails) {
		this.projectDetails = projectDetails;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectId))
			return false;
		ProjectId castOther = (ProjectId) other;

		return ((this.getProjectId() == castOther.getProjectId()) || (this
				.getProjectId() != null && castOther.getProjectId() != null && this
				.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getProjectName() == castOther.getProjectName()) || (this
						.getProjectName() != null
						&& castOther.getProjectName() != null && this
						.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getProjectDetails() == castOther.getProjectDetails()) || (this
						.getProjectDetails() != null
						&& castOther.getProjectDetails() != null && this
						.getProjectDetails().equals(
								castOther.getProjectDetails())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37
				* result
				+ (getProjectName() == null ? 0 : this.getProjectName()
						.hashCode());
		result = 37
				* result
				+ (getProjectDetails() == null ? 0 : this.getProjectDetails()
						.hashCode());
		return result;
	}

}
