// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private ProjectId id;

	public Project() {
	}

	public Project(ProjectId id) {
		this.id = id;
	}

	public ProjectId getId() {
		return this.id;
	}

	public void setId(ProjectId id) {
		this.id = id;
	}

}
