// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * TimesheetId generated by hbm2java
 */
public class TimesheetId implements java.io.Serializable {

	private String empId;
	private String timesheetId;
	private String cycleDate;
	private String sun;
	private String mon;
	private String tue;
	private String wed;
	private String thurs;
	private String fri;
	private String sat;
	private String vendorId;

	public TimesheetId() {
	}

	public TimesheetId(String empId, String timesheetId, String cycleDate,
			String sun, String mon, String tue, String wed, String thurs,
			String fri, String sat, String vendorId) {
		this.empId = empId;
		this.timesheetId = timesheetId;
		this.cycleDate = cycleDate;
		this.sun = sun;
		this.mon = mon;
		this.tue = tue;
		this.wed = wed;
		this.thurs = thurs;
		this.fri = fri;
		this.sat = sat;
		this.vendorId = vendorId;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getTimesheetId() {
		return this.timesheetId;
	}

	public void setTimesheetId(String timesheetId) {
		this.timesheetId = timesheetId;
	}

	public String getCycleDate() {
		return this.cycleDate;
	}

	public void setCycleDate(String cycleDate) {
		this.cycleDate = cycleDate;
	}

	public String getSun() {
		return this.sun;
	}

	public void setSun(String sun) {
		this.sun = sun;
	}

	public String getMon() {
		return this.mon;
	}

	public void setMon(String mon) {
		this.mon = mon;
	}

	public String getTue() {
		return this.tue;
	}

	public void setTue(String tue) {
		this.tue = tue;
	}

	public String getWed() {
		return this.wed;
	}

	public void setWed(String wed) {
		this.wed = wed;
	}

	public String getThurs() {
		return this.thurs;
	}

	public void setThurs(String thurs) {
		this.thurs = thurs;
	}

	public String getFri() {
		return this.fri;
	}

	public void setFri(String fri) {
		this.fri = fri;
	}

	public String getSat() {
		return this.sat;
	}

	public void setSat(String sat) {
		this.sat = sat;
	}

	public String getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimesheetId))
			return false;
		TimesheetId castOther = (TimesheetId) other;

		return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
				&& castOther.getEmpId() != null && this.getEmpId().equals(
				castOther.getEmpId())))
				&& ((this.getTimesheetId() == castOther.getTimesheetId()) || (this
						.getTimesheetId() != null
						&& castOther.getTimesheetId() != null && this
						.getTimesheetId().equals(castOther.getTimesheetId())))
				&& ((this.getCycleDate() == castOther.getCycleDate()) || (this
						.getCycleDate() != null
						&& castOther.getCycleDate() != null && this
						.getCycleDate().equals(castOther.getCycleDate())))
				&& ((this.getSun() == castOther.getSun()) || (this.getSun() != null
						&& castOther.getSun() != null && this.getSun().equals(
						castOther.getSun())))
				&& ((this.getMon() == castOther.getMon()) || (this.getMon() != null
						&& castOther.getMon() != null && this.getMon().equals(
						castOther.getMon())))
				&& ((this.getTue() == castOther.getTue()) || (this.getTue() != null
						&& castOther.getTue() != null && this.getTue().equals(
						castOther.getTue())))
				&& ((this.getWed() == castOther.getWed()) || (this.getWed() != null
						&& castOther.getWed() != null && this.getWed().equals(
						castOther.getWed())))
				&& ((this.getThurs() == castOther.getThurs()) || (this
						.getThurs() != null && castOther.getThurs() != null && this
						.getThurs().equals(castOther.getThurs())))
				&& ((this.getFri() == castOther.getFri()) || (this.getFri() != null
						&& castOther.getFri() != null && this.getFri().equals(
						castOther.getFri())))
				&& ((this.getSat() == castOther.getSat()) || (this.getSat() != null
						&& castOther.getSat() != null && this.getSat().equals(
						castOther.getSat())))
				&& ((this.getVendorId() == castOther.getVendorId()) || (this
						.getVendorId() != null
						&& castOther.getVendorId() != null && this
						.getVendorId().equals(castOther.getVendorId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmpId() == null ? 0 : this.getEmpId().hashCode());
		result = 37
				* result
				+ (getTimesheetId() == null ? 0 : this.getTimesheetId()
						.hashCode());
		result = 37 * result
				+ (getCycleDate() == null ? 0 : this.getCycleDate().hashCode());
		result = 37 * result
				+ (getSun() == null ? 0 : this.getSun().hashCode());
		result = 37 * result
				+ (getMon() == null ? 0 : this.getMon().hashCode());
		result = 37 * result
				+ (getTue() == null ? 0 : this.getTue().hashCode());
		result = 37 * result
				+ (getWed() == null ? 0 : this.getWed().hashCode());
		result = 37 * result
				+ (getThurs() == null ? 0 : this.getThurs().hashCode());
		result = 37 * result
				+ (getFri() == null ? 0 : this.getFri().hashCode());
		result = 37 * result
				+ (getSat() == null ? 0 : this.getSat().hashCode());
		result = 37 * result
				+ (getVendorId() == null ? 0 : this.getVendorId().hashCode());
		return result;
	}

}
