// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Timesheet generated by hbm2java
 */
public class Timesheet implements java.io.Serializable {

	private TimesheetId id;

	public Timesheet() {
	}

	public Timesheet(TimesheetId id) {
		this.id = id;
	}

	public TimesheetId getId() {
		return this.id;
	}

	public void setId(TimesheetId id) {
		this.id = id;
	}

}
