// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * VendorClientProject generated by hbm2java
 */
public class VendorClientProject implements java.io.Serializable {

	private VendorClientProjectId id;

	public VendorClientProject() {
	}

	public VendorClientProject(VendorClientProjectId id) {
		this.id = id;
	}

	public VendorClientProjectId getId() {
		return this.id;
	}

	public void setId(VendorClientProjectId id) {
		this.id = id;
	}

}
