// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vendor generated by hbm2java
 */
public class Vendor implements java.io.Serializable {

	private VendorId id;

	public Vendor() {
	}

	public Vendor(VendorId id) {
		this.id = id;
	}

	public VendorId getId() {
		return this.id;
	}

	public void setId(VendorId id) {
		this.id = id;
	}

}
