// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VendorClientProjectId generated by hbm2java
 */
public class VendorClientProjectId implements java.io.Serializable {

	private String vendorId;
	private String clientId;
	private String projectId;
	private Date validTill;

	public VendorClientProjectId() {
	}

	public VendorClientProjectId(String vendorId, String clientId,
			String projectId, Date validTill) {
		this.vendorId = vendorId;
		this.clientId = clientId;
		this.projectId = projectId;
		this.validTill = validTill;
	}

	public String getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public Date getValidTill() {
		return this.validTill;
	}

	public void setValidTill(Date validTill) {
		this.validTill = validTill;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendorClientProjectId))
			return false;
		VendorClientProjectId castOther = (VendorClientProjectId) other;

		return ((this.getVendorId() == castOther.getVendorId()) || (this
				.getVendorId() != null && castOther.getVendorId() != null && this
				.getVendorId().equals(castOther.getVendorId())))
				&& ((this.getClientId() == castOther.getClientId()) || (this
						.getClientId() != null
						&& castOther.getClientId() != null && this
						.getClientId().equals(castOther.getClientId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this
						.getProjectId() != null
						&& castOther.getProjectId() != null && this
						.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getValidTill() == castOther.getValidTill()) || (this
						.getValidTill() != null
						&& castOther.getValidTill() != null && this
						.getValidTill().equals(castOther.getValidTill())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVendorId() == null ? 0 : this.getVendorId().hashCode());
		result = 37 * result
				+ (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result
				+ (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result
				+ (getValidTill() == null ? 0 : this.getValidTill().hashCode());
		return result;
	}

}
