// default package
// Generated Feb 17, 2015 9:43:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Visa generated by hbm2java
 */
public class Visa implements java.io.Serializable {

	private VisaId id;

	public Visa() {
	}

	public Visa(VisaId id) {
		this.id = id;
	}

	public VisaId getId() {
		return this.id;
	}

	public void setId(VisaId id) {
		this.id = id;
	}

}
